services:
  tourney:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://tourney:tourney@db/tourney
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/Tourney
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - .data/Tourney/logs:/var/log/Tourney
      - .data/Tourney/uploads:/var/uploads
      - .:/opt/Tourney:ro
    depends_on:
      permissions:
        condition: service_completed_successfully
      db:
        condition: service_started
      cache:
        condition: service_started
    networks:
        default:
        internal:

  # TODO: Tourney 4.0 Migrate to named volumes. Users will likely need to manually migrate existing files
  permissions:
    image: alpine:3.23
    user: root
    volumes:
      - .data/Tourney/logs:/var/log/Tourney
      - .data/Tourney/uploads:/var/uploads
    command: chown -R 1001:1001 /var/uploads /var/log/Tourney

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./conf/nginx/http.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - tourney

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=tourney
      - MARIADB_USER=tourney
      - MARIADB_PASSWORD=tourney
      - MARIADB_DATABASE=tourney
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        internal:

networks:
    default:
    internal:
        internal: true
